# Generated by Django 2.2.5 on 2020-12-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20201227_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='select category', max_length=200),
        ),
    ]
